name: Test Deploy Hook

on:
  push:
    branches: develop

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Backend Deploy Hook (Debug only)
        run: echo "::debug::${RENDER_DEPLOY_HOOK_BACKEND}"
        env:
          RENDER_DEPLOY_HOOK_BACKEND: ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}

      - name: Curl Backend Hook
        run: |
          echo "Pinging: $RENDER_DEPLOY_HOOK_BACKEND"
          curl "$RENDER_DEPLOY_HOOK_BACKEND"
        env:
          RENDER_DEPLOY_HOOK_BACKEND: ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
