name: Deploy Both Services to Render

on:
  push:
    branches:
      - develop  # Adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy for Backend
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}

      - name: Trigger Deploy for Frontend
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
